# Generated by Django 6.0.2 on 2026-02-18 16:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('decision_schema_json', models.JSONField(default=dict)),
                ('config_json', models.JSONField(default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF'), ('other', 'Other')], max_length=16)),
                ('uri', models.TextField()),
                ('sort_key', models.CharField(max_length=255)),
                ('metadata_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed'), ('expired', 'Expired')], max_length=16)),
                ('mode', models.CharField(default='labels_only', max_length=32)),
                ('label_policy', models.CharField(default='latest_per_user', max_length=32)),
                ('format', models.CharField(default='jsonl', max_length=16)),
                ('filters_json', models.JSONField(default=dict)),
                ('include_fields_json', models.JSONField(default=list)),
                ('manifest_json', models.JSONField(blank=True, null=True)),
                ('file_uri', models.TextField(blank=True)),
                ('expires_at', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.BigIntegerField()),
                ('completed_at', models.BigIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('requested_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionLatest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField()),
                ('decision_id', models.CharField(max_length=64)),
                ('note', models.CharField(blank=True, max_length=2000)),
                ('ts_client', models.BigIntegerField()),
                ('ts_client_effective', models.BigIntegerField()),
                ('ts_server', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.item')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField()),
                ('decision_id', models.CharField(max_length=64)),
                ('note', models.CharField(blank=True, max_length=2000)),
                ('ts_client', models.BigIntegerField()),
                ('ts_client_effective', models.BigIntegerField()),
                ('ts_server', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.item')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('reviewer', 'Reviewer'), ('viewer', 'Viewer')], max_length=16)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant_key', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=128)),
                ('uri', models.TextField()),
                ('sort_order', models.IntegerField()),
                ('metadata_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.item')),
            ],
            options={
                'indexes': [models.Index(fields=['item', 'sort_order', 'variant_key'], name='django_app__item_id_f0e318_idx')],
                'unique_together': {('item', 'variant_key')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('reviewer', 'Reviewer'), ('viewer', 'Viewer')], max_length=16)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('organization', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['project', 'sort_key', 'id'], name='django_app__project_2facf9_idx'),
        ),
        migrations.AddIndex(
            model_name='exportjob',
            index=models.Index(fields=['project', 'created_at', 'id'], name='django_app__project_6e2773_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionlatest',
            index=models.Index(fields=['project', 'user', 'item'], name='django_app__project_014e51_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='decisionlatest',
            unique_together={('project', 'user', 'item')},
        ),
        migrations.AddIndex(
            model_name='decisionevent',
            index=models.Index(fields=['project', 'user', 'event_id'], name='django_app__project_39f0ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='decisionevent',
            unique_together={('project', 'user', 'event_id')},
        ),
        migrations.AlterUniqueTogether(
            name='projectmembership',
            unique_together={('project', 'user')},
        ),
    ]
